export const WORKS = [
  {
    id: 'history-lesson',
    title: 'History Lesson',
    year: '2024',
    video: 'MvuDW0qrUQ8',
    performers: 'Rezi Gvaramadze & George Namgaladze',
    text: `The exhibition consisted of three interconnected parts, each exploring the ways history is learned, distorted, and experienced through different lenses.\n\nAt its center were painted portraits of Georgian political figures, both historical and contemporary. These canvases were intentionally reworked and altered in the playful, irreverent manner of a middle-school student doodling in a history textbook.\n\nThe longest-running lesson in modern history has persisted for more than three decades, and still, no one knows when the bell will finally ring.`,
  },
  {
    id: 'microscope',
    title: 'Thank you very much for giving me this microscope!',
    year: '2023',
    video: 'bhVFKxd0dY4',
    performers: 'MATERIAL HUNTERS',
    text: `Part of the festival on decolonialism, this performance took place in the format of a trashy, absurd TV show, deliberately poking fun at the ways we view global politics, art, and the space from which we speak. \n\nIn this absurd and chaotic structure, we criticized how colonialism has shaped our perceptions of language, space, and identity. The performance’s aim was not to offer solutions, but to demonstrate the dissonance between intention and execution, to expose how the structures we operate within are deeply colonial and often impossible to untangle.`,
  },
  {
    id: 'mother-sisters',
    title: 'Your Mother and Your Sisters Against All',
    year: '2023',
    video: 'Fbm-mt3hDzI',
    performers: 'Mariam Karchkhadze',
    text: `All we know is that the performance combines biographical video documentation with live action. One of the video materials, dating back to 2019, features a narrator recalling in detail a tragic event from 2015.\n\nAfter seeing all this, I hope you will understand who your mother and sisters really are.`,
  },
  {
    id: 'subaltern',
    title: 'Subaltern Is Speaking',
    year: '2023',
    video: 'fhqaQBp00r0',
    performers: 'George Namgaladze',
    text: `Dedicated to Gayatri Chakravorty Spivak.\n\nWhat does contemporary Georgian art speak about itself in the Georgian language?\nWhy do they speak?\nWho speaks and who remains silent?\nIs it important to be sincere in front of the camera and then on the screen?\nWhich screen is being referred to?`,
  },
  {
    id: 'piano-porte',
    title: 'Piano Porte',
    year: '2023',
    video: 'ANQmFTBcpFA',
    performers: 'Demna Dalakishvili',
    text: `Audio-Visual performance by Demna Dalakishvili. The exploration of sound and decay.`,
  },
  {
    id: 'rites',
    title: '1, 147.142 Rites',
    year: '2023',
    video: '32_puyX8Qgg',
    performers: 'Natalia Nebieridze & Sophia Khundadze',
    text: `1,147.142 Rites - is an performative act by Natalia and her 11 years old daughter. Over the last 11 years, this act has been constantly repeated by them in a reversed form. The act was performed on a colorful floor installation, built especially for this performance.`,
  },
  {
    id: 'sit',
    title: 'SIT',
    year: '2022',
    video: 'kPPgzGNAhiM',
    performers: 'MATERIAL HUNTERS with their mothers',
    text: `The time has come for us to become madmen in your chain. In a world where war threatens us with extinction, a reality where social catastrophes take their toll on our souls, it is essential to find ways to each other.\n\nWhat do we call performing? We call it reduction. Reduction of doing, reduction of simulation, reduction of performing itself. Trying to disappear. Not to hide, but to sit and think about the long-range definition of love.`,
  },
  {
    id: 'naphetvrebi',
    title: 'Naphetvrebi, 15th str. House 29',
    year: '2022',
    video: 'XszA2wqNunc',
    performers: 'Rezi Gvaramadze & George Namgaladze',
    text: `It’s been a year since circumstances turned in the way that two lonesome humans became cohabitants. House that existed before those two, objects that simply were and are there where they are, in our mind cannot describe what we call home. \n\nFor the exhibition, the house will be wrapped, sliced, inflated and hidden away, in an attempt to explain its metaphysics-place where real cohabitation takes place.`,
  },
  {
    id: 'holy-slip',
    title: 'Holy Slip',
    year: '2021-2022',
    video: 'IjBy2YUMKj8',
    performers: 'MATERIAL HUNTERS',
    text: `31 December - 1 January. On New Year's Eve at Haraki Theatre, we staged an eight-hour immersive performance. \n\nBeginning at 10 PM on December 31st, we slept through the cultural threshold of the new year, embodying vulnerability and trust in a shared space. A sleeping person is at their most open and defenseless, and by resting publicly, we invited visitors to witness and engage with this state.`,
  },
  {
    id: 'is-that-all',
    title: 'Is that all there is?',
    year: '2021',
    video: 'EXZJsFptTHI',
    performers: 'MATERIAL HUNTERS',
    text: `Musical performance within the frames of MAUDI Live Action. The five experimental numbers are based on the synthesis of music and performance mediums, as well as attempts and practices to deconstruct linguistic expressions.`,
  },
  {
    id: 'show',
    title: 'MATERIAL HUNTERS SHOW',
    year: '2019',
    video: 'Ru6ZBdcM8DA',
    performers: 'MATERIAL HUNTERS',
    text: `Pam pam parampo, pam dam. \nart? \nforget it.\n\nThe legendary collective Material Hunter presents an amazing and surprise show program! At the show, you will see a deadly number - boys running on the edge of a knife; Iron press girl on rubber rope; melodramatic film-adventure; to many dead and living. \n\nConsumption is not a basic instinct and it has no value.`,
  },
  {
    id: 'jump-to-love',
    title: 'I dedicate this jump to love',
    year: '2018',
    video: '-_uST4ildes',
    performers: 'MATERIAL HUNTERS',
    text: `The groaning of contractions, to describe the boundless poetry of the universe. \n\nEverything in which you live your life is mere waste, and we are its clearest example. The unrelenting desire to become waste, to be discarded, to embrace the stench—reveals the purity that has manifested before you in our form.`,
  },
];
